---
title: "Systematic Review Extraction Script Template"
date: "26 Jun 2018 at 16:07:01"
output:
  html_document:
    self-contained: yes
    toc: false
params:
  rxsVersion = "0.1.0"
---

```{r setup, include=FALSE}
### First load (and perhaps install) userfriendlyscience
if (!require('userfriendlyscience')) {
  install.packages('userfriendlyscience');
  require('userfriendlyscience');
}

### Other packages
safeRequire('googlesheets');     ### To import data from google sheets in metabefor
safeRequire('jsonlite');         ### To import a list of country codes in metabefor
safeRequire('data.tree');        ### To work with data structured in a tree in metabefor
safeRequire('pander');           ### To print the dataframe with results in a nice way
safeRequire('devtools');         ### To install metabefor from github repo
                                 ### ... Which we then do here:
devtools::install_github('Matherion/metabefor', quiet=TRUE);
require('metabefor');            ### ... After which we load it

### Settings
knitr::opts_chunk$set(echo = FALSE);             ### Suppress R command printing
knitr::opts_chunk$set(comment=NA);               ### Suppress output prefix
pander::panderOptions('table.split.table', Inf); ### Disable table splitting
```

```{r fieldname-chunk}
eC <- list(titleCol="title",
           descriptionCol="description",
           identifierCol="identifier",
           valueTemplateCol="valueTemplate",
           validValuesCol="validValues",
           defaultCol="default",
           parentCol="parent",
           entityRefCol="entityRef",
           fieldRefCol="fieldRef",
           ownerCol="owner",
           listCol="list",
           collapsingCol="collapsing",
           repeatingCol="repeating",
           recursingCol="recursing");

valueTemplateCols <- list(identifierCol="identifier",
                          descriptionCol="description",
                          defaultCol="default",
                          examplesCol="examples",
                          validationCol="validation",
                          errorCol="error");
```

```{r rxsChunk, echo=FALSE}
################################################################################
######################################################## START: study (ROOT) ###
################################################################################
study <- Node$new('study');
################################################################################

  ##############################################################################
  ########################################################### START: studyId ###
  ##############################################################################
  study$AddChild('studyId');
  study$studyId[['value']] <-
  ##############################################################################
  ### 
  ### STUDY IDENTIFIER
  ### 
  ### Unique identifier for this study
  ### 
  ##############################################################################
      
      "10.1080/1612197X.2014.932826"
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### For studies with a DOI, "doi:" directly followed by the DOI; for
  ### studies without a DOI, the DOI prefix of the publisher (see
  ### https://gist.github.com/TomDemeranville/8699224), followed by a
  ### slash, followed by the ISSN, followed by a dash, followed by the
  ### year of publication, followed by a dash, followed by the starting
  ### page. If no DOI prefix can be located, instead use 'NA'.
  ### 
  ### EXAMPLES:
  ### 
  ### "doi:10.18637/jss.v036.i03"
  ### "nodoi:10.1111/0965-2140/2003-951"
  ### "doi:10.1136/bmj.2.2288.1243"
  ### 
  ##############################################################################
  study$studyId[['validation']] <- expression(nchar(VALUE)>10);
  ##############################################################################
  ############################################################# END: studyId ###
  ##############################################################################


  ##############################################################################
  ########################################################## START: comments ###
  ##############################################################################
  study$AddChild('comments');
  study$comments[['value']] <-
  ##############################################################################
  ### 
  ### GENERAL COMMENTS
  ### 
  ### Any general comments the coder wants to add about this study
  ### 
  ##############################################################################
      
      ""
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A single character value
  ### 
  ### EXAMPLES:
  ### 
  ### "Example"
  ### "Another example"
  ### 
  ##############################################################################
  study$comments[['validation']] <- expression(is.character(VALUE) && length(VALUE) == 1);
  ##############################################################################
  ############################################################ END: comments ###
  ##############################################################################


  ##############################################################################
  ############################################################## START: year ###
  ##############################################################################
  study$AddChild('year');
  study$year[['value']] <-
  ##############################################################################
  ### 
  ### YEAR
  ### 
  ### Year (or years) the data were collected
  ### 
  ##############################################################################
      
      2014
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A numeric vector of years
  ### 
  ### EXAMPLES:
  ### 
  ### 2001
  ### c(2001, 2002)
  ### 
  ##############################################################################
  study$year[['validation']] <- expression(is.numeric(VALUE) && all(nchar(VALUE)==4));
  ##############################################################################
  ################################################################ END: year ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: country ###
  ##############################################################################
  study$AddChild('country');
  study$country[['value']] <-
  ##############################################################################
  ### 
  ### COUNTRY
  ### 
  ### Country (or countries) where the data were collected
  ### 
  ##############################################################################
      
      "GB"
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A character vector of the ISO 3166-1 alpha-2 country code(s)
  ### 
  ### EXAMPLES:
  ### 
  ### "NL"
  ### c("NL", "BE")
  ### 
  ##############################################################################
  study$country[['validation']] <- expression(VALUE %in% countryCodeList());
  ##############################################################################
  ############################################################# END: country ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: methods ###
  ##############################################################################
  study$AddChild('methods');
  ##############################################################################
  ### 
  ### METHODS
  ### 
  ### Description of the methods used by the study
  ### 
  ##############################################################################
      
  
    ############################################################################
    ############################################################### START: N ###
    ############################################################################
    study$methods$AddChild('N');
    study$methods$N[['value']] <-
    ############################################################################
    ### 
    ### SAMPLE SIZE
    ### 
    ### Total number of human participants in the study (note: the
    ### actual sample size may be larger if multiple observations are
    ### collected per participant)
    ### 
    ############################################################################
        
        9
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ############################################################################
    study$methods$N[['validation']] <- expression(is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1));
    ############################################################################
    ################################################################# END: N ###
    ############################################################################
  
  
    ############################################################################
    ########################################################### START: Ntype ###
    ############################################################################
    study$methods$AddChild('Ntype');
    study$methods$Ntype[['value']] <-
    ############################################################################
    ### 
    ### SAMPLE SIZE TYPE
    ### 
    ### Whether the sample size counts the number of persons or the
    ### number of matches
    ### 
    ############################################################################
        
        "person"
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A string that has to exactly match one of the values specified
    ### in the "values" column of the Coding sheet
    ### 
    ### EXAMPLES:
    ### 
    ### "person"
    ### "match"
    ### 
    ############################################################################
    study$methods$Ntype[['validation']] <- expression(VALUE %in% c("person", "match"));
    ############################################################################
    ############################################################# END: Ntype ###
    ############################################################################
  
  
    ############################################################################
    ########################################### START: subsample (REPEATING) ###
    ############################################################################
    study$methods$AddChild('subsample__1__');
    study$methods$subsample__1__[['value']] <-
    ############################################################################
    ### 
    ### SUBSAMPLE
    ### 
    ### If studies contain several samples, specify them here
    ### 
    ############################################################################
        
        list(subsample.name = "Enter name here (mandatory)",  ### Name: A unique name (in this study), to be able to refer to this subsample later, and to easily find it afterwards [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             subsample.N = NA,                                ### Size: Sample size of subsample [Examples: 30; 8762] [Value description: Any valid whole number]
             subsample.Ntype = NA);                           ### Sample size type: Whether the sample size counts the number of persons or the number of matches [Examples: "person"; "match"; "season"] [Value description: A string that has to exactly match one of the values specified in the "values" column of the Coding sheet]
        
    ############################################################################
    study$methods$subsample__1__[['validation']] <- list(`subsample.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                         `subsample.N` = expression(is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)),
                                                         `subsample.Ntype` = expression(VALUE %in% c("person", "match", "season")));
    study$methods$subsample__1__$name <- study$methods$subsample__1__$value[[1]];
    ############################################################################
    ############################################# END: subsample (REPEATING) ###
    ############################################################################
  
  
    ############################################################################
    ###################################################### START: methodType ###
    ############################################################################
    study$methods$AddChild('methodType');
    study$methods$methodType[['value']] <-
    ############################################################################
    ### 
    ### TYPE OF STUDY
    ### 
    ### Whether the study was qualitative or quantitative
    ### 
    ############################################################################
        
        "qualitative"
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A string that has to exactly match one of the values specified
    ### in the "values" column of the Coding sheet
    ### 
    ### EXAMPLES:
    ### 
    ### "qualitative"
    ### "quantitative"
    ### "mixed methods"
    ### 
    ############################################################################
    study$methods$methodType[['validation']] <- expression(VALUE %in% c("qualitative", "quantitative", "mixed methods"));
    ############################################################################
    ######################################################## END: methodType ###
    ############################################################################
  
  
    ############################################################################
    ############################################# START: operationalisations ###
    ############################################################################
    study$methods$AddChild('operationalisations');
    ############################################################################
    ### 
    ### OPERATIONALISATIONS
    ### 
    ### The operationalisations (measurements or manipulations) used in
    ### the study
    ### 
    ############################################################################

  ##############################################################################
  ############################################################# END: methods ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: results ###
  ##############################################################################
  study$AddChild('results');
  ##############################################################################
  ### 
  ### RESULTS
  ### 
  ### Results based on the data collected in this study
  ### 
  ##############################################################################
      
  
    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameLocation",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "homeLocation",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "My experience tells me as well that sometimes players will give an extra 5–10% playing at home than not and so that enthuses on the amount of desire that will be created at home because they have the home supporters and ... . home is convenient sometimes playing away from home it can be ... . a smaller dressing room it can be worse conditions, worse pitch so I think sometimes the convenience of playing at home helps.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################
  
      
    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameLocation",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "awayLocation",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "When you play in some old stadium like X or X you know it’s not very nice ... .unfortunately you have to play at home and away. For me I don’t like to play away, it would be perfect to play at home, all the games at home");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################

    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameFactors",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "crowd",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "I think the crowds were fantastic really, and I think even when the players probably weren’t er ... at their best I think the crowd lifted them to you know give that little bit more which I think all the good crowds do");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameFactors",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "familiarity",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "It’s a more familiar feeling, the people when you get there the parking in your own parking place all the way through to like I say familiarity of seeing people you’re comfortable with, and the fact that if you need anything there’s a 99.9% chance you get it.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameFactors",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "territoriality",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "It was more like home because I spent most of my time there ... you know you’re there on a daily basis the fixtures and fittings becomes second nature. The changing rooms, the corridors, the going out on to the pitch, the pitch itself it becomes part of what you’re about.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################  


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameFactors",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "travel",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "If we’ve got to go away a longer distance we travel the day before, sleep in hotels and that’s a bit different, but you’re still quite well rested and things. I don’t really like travelling on the day of games and we have done that a couple of times if it’s only an hour, hour and a half but I prefer to be at home, or travel overnight, I’m not a fan of travelling on the day.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "gameFactors",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "referee",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = " think the home fans when they put pressure for 90 minutes on the referee ... they can affect him ... little decisions you know when like you have someone fall on the floor in the box and you have 50,000 fans start to boo or you know to do some noise it can affect the referee. I think the fans can help you get something from the referee.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "physiologicalState",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "physiological",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "Yeah I think you’re definitely aware of it when things go well because I think you ... you know get that adrenalin surge because you are doing well and the crowd respond.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "PsychologicalState",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "anxiety",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "You get some teams that are more abusive, get more behind their team it sort of depends if you play at X if you come on as a sub and warm up on the side you just get loads of abuse you do have places that are more like that.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "CriticalBehavioralState",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "experience",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "I’ve got my kids, family, just go home and you can just walk through the door and forget. I think there are some players and I didn’t used to be able to forget when I was younger. Now, experience that does help you put things in perspective but you do still think about things. What’s helped me is being able to do that, in the past when I’ve had a lot of time and gone home should have done this, you can beat yourself up. I don’t like to think about it too much as I can’t do anything about it");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


    ############################################################################
    ########################################## START: univariate (REPEATING) ###
    ############################################################################
    study$results$AddChild('univariate__1__');
    study$results$univariate__1__[['value']] <-
    ############################################################################
    ### 
    ### UNIVARIATE
    ### 
    ### A univariate result, e.g. a quote in a qualitative study
    ### 
    ############################################################################
        
        list(uni.name = "CriticalBehavioralState",  ### Name of result: A unique name (in this study), to easily find / meta-analyse / group this result later [Examples: "Example"; "Another example"] [Value description: A single character value that cannot be omitted]
             uni.varname = "tactics",               ### Name of variable: The variable this result pertains to. [Examples: <no example>] [Value description: A string that specifies another entity and which MUST be provided]
             uni.qualitative = "I think sometimes you can see some big differences when the team plays at home to away ... like I think you attack more when you play at home and defend more when you play away.");                     ### Qualitative observation: A quote of a participant in a qualitative study or an observation by the authors in a qualitative study. [Examples: "Example"; "Another example"] [Value description: A single character value]
        
    ############################################################################
    study$results$univariate__1__[['validation']] <- list(`uni.name` = expression(!is.na(VALUE) && !is.null(VALUE) && (nchar(VALUE) > 0)),
                                                          `uni.varname` = expression(TRUE),
                                                          `uni.qualitative` = expression(is.character(VALUE) && length(VALUE) == 1));
    study$results$univariate__1__$name <- study$results$univariate__1__$value[[1]];
    ############################################################################
    ############################################ END: univariate (REPEATING) ###
    ############################################################################


  ##############################################################################
  ############################################################# END: results ###
  ##############################################################################


  ##############################################################################
  #################################################### START: assoc.nMatches ###
  ##############################################################################
  study$AddChild('assoc.nMatches');
  study$assoc.nMatches[['value']] <-
  ##############################################################################
  ### 
  ### NUMBER OF MATCHES
  ### 
  ### The number of matches to which the association pertains.
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### Any valid whole number
  ### 
  ### EXAMPLES:
  ### 
  ### 30
  ### 8762
  ### 
  ##############################################################################
  study$assoc.nMatches[['validation']] <- expression(is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1));
  ##############################################################################
  ###################################################### END: assoc.nMatches ###
  ##############################################################################

    
################################################################################
########################################################## END: study (ROOT) ###
################################################################################
class(study) <- c('rxs', class(study));
```

```{r show-extracted-data-chunk, results='asis'}
print.rxs(study);
```

```{r validation-chunk, results='asis'}
rxs_validation(study);
cat0("\n\n### Validation results\n\n");
#rxs_validation(study,
#               rxsStructure = fullResults$rxsStructure);
if (length(study$validationResults) > 2) {
  cat(paste0('- ', study$validationResults), sep='
');
} else {
  cat('Validation successful!');
}
```

